deployment:
  tasks:
    - source /home/your_user/virtualenv/myapp/3.x/bin/activate
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - touch tmp/restart.txt