deployment:
  tasks:
    - source /home/dkkatlcy/virtualenv/portfolio_backend/3.11/bin/activate && cd /home/dkkatlcy/portfolio_backend
    - pip install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - touch tmp/restart.txt