# Generated by Django 5.2.4 on 2025-07-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdruhuldev', '0002_aboutsection_contactmessage_locationsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='section',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
