# Generated by Django 5.2.4 on 2025-07-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdruhuldev', '0003_technology_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsection',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locationsection',
            name='whats_app',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
