# Generated by Django 5.2.4 on 2025-07-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdruhuldev', '0004_locationsection_facebook_locationsection_whats_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationsection',
            old_name='facebook',
            new_name='codechef_link',
        ),
        migrations.AddField(
            model_name='locationsection',
            name='codeforces_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locationsection',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locationsection',
            name='others_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
