# Generated by Django 5.2.4 on 2025-07-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdruhuldev', '0005_rename_facebook_locationsection_codechef_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationsection',
            old_name='others_link',
            new_name='personal_website',
        ),
    ]
